spring.application.name=MusicStore

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/music_store
spring.datasource.username=postgres
spring.datasource.password=190605
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080

# Emailspring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=<login user to smtp server>
spring.mail.password=<login password to smtp server>
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
